config:
  guestbook_name: "MyPopRock Festival 2.0"
  backend_uri: "http://backend.minikube.local/guestbook"

replicaCount: 1

image:
  # Whenever we have to update the image version, just use the tag
  repository: phico/frontend
  tag: "2.0"

service:
  port: 80
  type: ClusterIP

ingress:
  enabled: true
  host: frontend.minikube.local